app: 
  name: "go-hexagonal-architecture"

web:
  prefork: false
  port: 3000

log:
  level: 6

database: 
  username: "root"
  password: "root"
  host: "localhost"
  port: 3306
  name: "go_hexagonal_architecture"
  pool:
    idle: 10
    max:  100
    lifetime: 300